# development:
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   url: postgres://u143eepoiv25uu:paosfb5jfooact22habkr9i7r04@ec2-52-213-203-153.eu-west-1.compute.amazonaws.com:5432/dcr1n0n8bv3dba

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  pool: 5
  timeout: 5000
  database: <%= ENV.fetch("DATABASE_NAME", "trayder") %>

test:
  adapter: postgresql
  encoding: unicode
  host: 0.0.0.0
  username: postgres
  pool: 5
  timeout: 5000
  database: <%= ENV.fetch("DATABASE_NAME", "trayder") %>

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  sslmode: require
  url: <%= ENV["DATABASE_URL"] %>
  checkout_timeout: 10
  reaping_frequency: 10
  dead_connection_timeout: 30
